### ISSUE TITLE
Allow use revealPasswordButton classes in read-only state of TextBox

### ISSUE THREAD

**Issue by CIRCULARKA** [AvaloniaCommunity/Material.Avalonia#157]
Can you make ```revealPasswordButton``` show up even if control is read only?
I want to add readonly ```TextBox``` to my app but do not want users to input anything in it. Also I need functionality of button above because there is must be a secret key inside of TextBox.
My code is:
![image](https://user-images.githubusercontent.com/34581740/153594044-84a2e875-f515-482c-97f7-b863dc9de080.png)

When I add ```IsReadOnly="True"``` show/hide button dissapears. Maybe there is another approach to achieve what I want? 

I am using ```2.5.0.72-nightly``` version of package

**Comment by appleneko2001** [comment]
Hi @CIRCULARKA !
I did a little bit changes on TextBox styles. This issue is reasonal for me too. You should be able to use if you use latest nightly package of Material.Avalonia!

Commit: https://github.com/AvaloniaCommunity/Material.Avalonia/commit/fb9541bbbd034daf4d321d42f3b84775736165cd

**Comment by CIRCULARKA** [comment]
Thats worked, thanks. But there is another question: when I switch back to "hidden" mode I end up with NullReferenceException
It was on *.72 and on *.73 version

**Comment by SKProCH** [comment]
Hello, @CIRCULARKA 

Can you post Exception stacktrace, and any other related data, if possible? 
Also you share your project for problem investigation.

**Comment by CIRCULARKA** [comment]
> Hello, @CIRCULARKA
> 
> Can you post Exception stacktrace, and any other related data, if possible? Also you share your project for problem investigation.

I'll better give you the whole project. Stack trace of an error in the ```error.txt``` file in the root
https://drive.google.com/drive/folders/13cGDZY4ohdzqwdctNVKb7SA2Z09fvVZx?usp=sharing

**Comment by CIRCULARKA** [comment]
UPD: Actually error occurs when I click "Show password" button and then leave my cursor from control

**Comment by appleneko2001** [comment]
Hi @CIRCULARKA ! Sorry for 2 months waiting:(

I downloaded your reproduce sample and updated to more recent version, but it works fine and no exception thrown. Looks like this issue is solved already.

Version of AvaloniaUI: 0.10.11
Material.Avalonia: 3.0.0-rc0

![Анимация](https://user-images.githubusercontent.com/38249047/163717954-cce28a0a-f3ee-408b-b7c4-bef86fa5bc8a.gif)

Might you try again with those version packages?

**Comment by CIRCULARKA** [comment]
> Hi @CIRCULARKA ! Sorry for 2 months waiting:( Those days I was busy and I forgot about this until today
> 
> I downloaded your reproduce sample and updated to more recent version, but it works fine and no exception thrown. Looks like this issue is solved already.
> 
> Version of AvaloniaUI: 0.10.11 Material.Avalonia: 3.0.0-rc0
> 
> ![Анимация](https://user-images.githubusercontent.com/38249047/163717954-cce28a0a-f3ee-408b-b7c4-bef86fa5bc8a.gif)
> 
> Might you try again with those version packages?

Hi, thanks for the answer. Yes, my problem actually gone, and I still don't why it ocurred, might be something with my windows manager or idk

**Comment by appleneko2001** [comment]
> > Hi @CIRCULARKA ! Sorry for 2 months waiting:( Those days I was busy and I forgot about this until today
> > I downloaded your reproduce sample and updated to more recent version, but it works fine and no exception thrown. Looks like this issue is solved already.
> > Version of AvaloniaUI: 0.10.11 Material.Avalonia: 3.0.0-rc0
> > ![Анимация](https://user-images.githubusercontent.com/38249047/163717954-cce28a0a-f3ee-408b-b7c4-bef86fa5bc8a.gif)
> > Might you try again with those version packages?
> 
> Hi, thanks for the answer. Yes, my problem actually gone, and I still don't why it ocurred, might be something with my windows manager or idk

Actually I added `bug` tag when I saw this problem. I have no idea how it occur. Might be something odd on our library and I fixed it without intension
